Create a Desktop Version of my Portfolio
Rizwan-learn/mod-1 pull request #1
Opened 2022-01-20 13:28 UTC by Rizwan-learn

2022-01-20 23:31 UTC, t-yanick requested changes
## STATUS: CHANGES REQUESTED ♻️ 
### Hi @Rizwan-learn , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-20 23:31 UTC, t-yanick commented on styles.css
> +  .flex__container {
- [x] As it is a requirement for this project and best practice, using the mobile first approach, your media queries for the desktop breakpoint value for `min-width` should be in the range `992px - 1100px`. So please, kindly go with the mobile first approach. Checkout this [article](https://www.freecodecamp.org/news/taking-the-right-approach-to-responsive-web-design/).
- [x] Please, as it is a requirement for this project, kindly ensure your mobile version still looks as expected(i.e. your app is still responsive). See screenshot of the requirements below. 
![mobileVersion](https://user-images.githubusercontent.com/62849872/150430572-2d84720c-d2c1-4bb9-8e3e-1892341d58d4.png)

2022-01-20 23:31 UTC, t-yanick commented on README.md
> +# 👤 Author1 <br>
- [ ] Since you're the only one working on this project, consider removing the `1` in `Author1`. This is to make your README perfectly professional.

2022-01-21 17:27 UTC, Rizwan-learn commented on styles.css
> +  .flex__container {
Hi I already Made it from A desktop version to Mobile Version can we still not accept this

2022-01-21 17:27 UTC, Rizwan-learn commented on README.md
> +# 👤 Author1 <br>
ReadMe Updated

2022-01-21 17:31 UTC, Rizwan-learn commented on styles.css
> +  .flex__container {
Sorry I made the mistake of making a new desktop version first then using Media Quires to update it to fix a mobile platform too. Think this should still be allowed a pass since its does fit the requirements

2022-01-21 17:42 UTC, Rustamxon7 approved these changes
## Hi @Rizwan-learn 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://i.pinimg.com/originals/77/0e/b0/770eb057449582c44672b2d2d1cc39b6.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-21 17:42 UTC, Rustamxon7 commented on index.html
> +    </section>
- [ ] [OPTIONAL] Nice job. I suggest some improvements to make you desing better. Please first make languages cards to left a bit to make look more like figma design. Please also add underlines to `Languages`, `Frameworks` and `Skills` text. Lastly I recommend adding icons to the right side of titles. You can see more details in screenshot below

#### Your desing
![image](https://user-images.githubusercontent.com/69011963/150574651-46060d6f-183d-4a29-88a4-840a0eb755fd.png)

2022-02-16 14:29 UTC, keroloussamy requested changes
Hi @Rizwan-learn, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 14:29 UTC, keroloussamy commented on styles.css
> +}
- [ ] Kindly change the `width: 130px;`, because it makes the page overflow.

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35535130/154284232-573a6e43-7aef-4806-8049-999e2681e7bd.png) | ![image](https://user-images.githubusercontent.com/35535130/154284450-b8b4e0fc-a028-4ee0-9a0d-0a7672e6f22a.png) |

2022-02-16 14:29 UTC, keroloussamy commented on styles.css
> +}
- [ ] Kindly change the `width: 569px;`, because it makes the page overflow. and the paragraph is not like the Figma design.

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35535130/154284232-573a6e43-7aef-4806-8049-999e2681e7bd.png) | ![image](https://user-images.githubusercontent.com/35535130/154284450-b8b4e0fc-a028-4ee0-9a0d-0a7672e6f22a.png) |

2022-02-17 09:27 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi @Rizwan-learn ,  

Your project is complete! Congratulations!  🎉💯🌟 

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />


Cheers and Happy coding! :clap: :clap: :clap:


------
Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 10:51 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @Rizwan-learn , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏
- [ ] In the future, make sure that you create a new repo or branch for a project even if you did it before or you repeated the week.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 10:51 UTC, RolandM99 commented on styles.css
> +  padding: 25px;
- [ ] [ OPTIONAL ] Good job by implementing a design very similar to the Figma template. But, while adding the desktop version, something changed in your mobile version. the space(margin) between cards disappeared : 
- your template:
![image](https://user-images.githubusercontent.com/71874425/154447106-5a0e9685-c90a-4f7c-813d-2e9527abdfd9.png)

- Figma template:
![image](https://user-images.githubusercontent.com/71874425/154460245-da38eda6-77d5-4c86-867c-20ad87ba9f4a.png)

- [ ] Kindly, fix it 🧑‍🔧

2022-02-17 10:58 UTC, merged