Pop ups for portfolio
Rizwan-learn/mod-1 pull request #8
Opened 2022-03-03 16:37 UTC by Rizwan-learn

2022-03-03 17:15 UTC, thecodechaser requested changes
## Hi @Rizwan-learn 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good accessibility report. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please use camel case for commit messages
Bad example: "add pop-up model"
Good example: "Add pop-up model

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 17:15 UTC, thecodechaser commented on pop-up.js
> +      </section>`;
- [ ] Good job working on the styles but still there is a little issue. You are supposed to stick to the [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) as much as possible. Your design is a little different from the template. Please fix the alignment of elements, fix the design, and make sure it matches the template.

Your design

![Screenshot (197)](https://user-images.githubusercontent.com/83803414/156614522-d239be51-3830-4bdd-8f27-b4f0ebbf1ca7.png)


Figma design

![Screenshot (198)](https://user-images.githubusercontent.com/83803414/156614485-7b741ceb-d0bb-4879-a9df-f7c6aeb55d8e.png)

2022-03-03 17:15 UTC, thecodechaser commented on pop-up.js
> +  }
- [ ]  For mobile pop-up model please remove the left margin from technologies,
- [ ]  Please reduce the gap between text and icon in buttons, Make sure everything match with the Figma design.

Your design

![Screenshot (202)](https://user-images.githubusercontent.com/83803414/156615321-91dd16c8-e64a-42ab-bfcf-64f4aa8b7d07.png)


Figma design

![Screenshot (201)](https://user-images.githubusercontent.com/83803414/156615291-ea061100-4d16-43c3-9706-63606c360b4b.png)

2022-03-03 18:30 UTC, thecodechaser requested changes
## Hi @Rizwan-learn 👋, 

Great work on making the changes requested by me 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 18:37 UTC, thecodechaser requested changes
## Hi @Rizwan-learn 👋, 

Great work on making the changes requested by me 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 18:37 UTC, thecodechaser commented on pop-up.js
> +}
[ ] As requested by me previously, Please fix the design and make sure it matches the template.
-  Please increase the width of your pop-up model and place some paddings
-  Please add a blur effect for the background as it is in the design.

Your design
![Screenshot (204)](https://user-images.githubusercontent.com/83803414/156630012-f241d74d-1a3c-4b19-9ae4-597b50b2ca4c.png)


Figma design

![Screenshot (198)](https://user-images.githubusercontent.com/83803414/156629683-6c01eb9c-429b-4af8-a774-0bca09b5402a.png)

2022-03-04 12:44 UTC, keroloussamy approved these changes
Hi @Rizwan-learn, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 15:40 UTC, merged